import { randomUUID } from 'crypto';
import { db } from '../db/client';
import { experiences } from '../db/schema';

async function seedExperiences() {
  console.log('Seeding experiences...');

  const now = new Date();
  const published = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86_400_000);

  const rows = [
    {
      id: randomUUID(),
      slug: 'visiting-the-egyptian-museum',
      type: 'visit',
      titleEn: 'A Morning at the Egyptian Museum',
      titleAr: 'صباح في المتحف المصري',
      summaryEn: 'An unforgettable walk through 5,000 years of history in the heart of Cairo.',
      summaryAr: 'جولة لا تُنسى عبر 5,000 سنة من التاريخ في قلب القاهرة.',
      contentEn: 'The Egyptian Museum in Tahrir Square is one of the most remarkable places I have ever visited. I arrived early in the morning before the crowds and spent three hours wandering through galleries filled with ancient artifacts. The Tutankhamun room alone is worth the entire trip — the golden mask is breathtaking in person. My guide, who has worked there for 20 years, shared stories that no guidebook captures.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Sara Ahmed',
      submittedByEmail: 'sara@example.com',
      status: 'published' as const,
      likeCount: 14,
      viewCount: 87,
      createdAt: published(10),
      publishedAt: published(9),
      updatedAt: published(9),
    },
    {
      id: randomUUID(),
      slug: 'book-review-cairo-trilogy',
      type: 'book_review',
      titleEn: 'Reading Naguib Mahfouz\'s Cairo Trilogy',
      titleAr: 'قراءة ثلاثية نجيب محفوظ',
      summaryEn: 'How three novels changed the way I see the city I was born in.',
      summaryAr: 'كيف غيّرت ثلاثة روايات نظرتي للمدينة التي وُلدت فيها.',
      contentEn: 'I had lived in Cairo all my life without truly seeing it. Then I read the Cairo Trilogy — Palace Walk, Palace of Desire, Sugar Street — and everything shifted. Mahfouz describes al-Gamaliyya district with such precision that I walked those streets with completely new eyes. The characters of al-Sayyid Ahmad Abd al-Jawad and his family felt as real as my own neighbors.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Mostafa Khalil',
      submittedByEmail: 'mostafa@example.com',
      status: 'published' as const,
      likeCount: 22,
      viewCount: 130,
      createdAt: published(7),
      publishedAt: published(6),
      updatedAt: published(6),
    },
    {
      id: randomUUID(),
      slug: 'road-trip-luxor-aswan',
      type: 'trip',
      titleEn: 'Five Days Along the Nile: Luxor to Aswan',
      titleAr: 'خمسة أيام على ضفاف النيل: الأقصر إلى أسوان',
      summaryEn: 'Temples, feluccas, and the endless sky — a journey that resets everything.',
      summaryAr: 'معابد وفلوكة وسماء لا نهاية لها — رحلة تُعيد ضبط كل شيء.',
      contentEn: 'We drove from Cairo to Luxor, stopping at Abydos and Dendera along the way. Karnak at sunrise with almost no one around is something I will never forget. Then south to Aswan — the Nubian villages, the sunset over the Nile, Abu Simbel at 4am with the sound of your own breath. Egypt outside the tourist bubble is a completely different country.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Nadia Hassan',
      submittedByEmail: 'nadia@example.com',
      status: 'published' as const,
      likeCount: 31,
      viewCount: 210,
      createdAt: published(5),
      publishedAt: published(4),
      updatedAt: published(4),
    },
    {
      id: randomUUID(),
      slug: 'cairo-jazz-club-event',
      type: 'event',
      titleEn: 'An Evening at Cairo Jazz Club',
      titleAr: 'أمسية في نادي القاهرة للجاز',
      summaryEn: 'Jazz in Arabic — where Coltrane meets maqam.',
      summaryAr: 'الجاز بالعربية — حيث يلتقي كولتريان بالمقام.',
      contentEn: 'The Cairo Jazz Club in Agouza is the best-kept secret in the city. I caught a live set by a young Egyptian quartet playing original compositions that blended Arabic maqamat with classic jazz harmony. The crowd was small, intimate, and deeply attentive. Drinks were reasonably priced, the acoustics were surprisingly good for a basement venue. I left at 1am and walked home feeling genuinely moved.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Youssef Ramadan',
      submittedByEmail: 'youssef@example.com',
      status: 'published' as const,
      likeCount: 9,
      viewCount: 55,
      createdAt: published(3),
      publishedAt: published(2),
      updatedAt: published(2),
    },
    {
      id: randomUUID(),
      slug: 'street-food-tour-downtown',
      type: 'visit',
      titleEn: 'Downtown Cairo Street Food: A Self-Guided Tour',
      titleAr: 'أكل الشارع في وسط البلد: جولة ذاتية',
      summaryEn: 'Koshary, feteer, hawawshi, and tea — one afternoon, five stops.',
      summaryAr: 'كشري وفطير وهواوشي وشاي — بعد ظهر واحد، خمس محطات.',
      contentEn: 'Start at Abou Tarek for koshary around noon. Walk north to Maidan Talaat Harb and get feteer from the small place on the corner. Continue to a hawawshi spot behind the old Cinema Diana. End at El Abd patisserie for basbousa and strong tea. Budget: roughly 80 EGP total. Time: 2-3 hours including walking. The streets of downtown are themselves part of the meal.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Laila Mansour',
      submittedByEmail: 'laila@example.com',
      status: 'pending' as const,
      likeCount: 0,
      viewCount: 0,
      createdAt: published(1),
      publishedAt: null,
      updatedAt: published(1),
    },
    {
      id: randomUUID(),
      slug: 'al-azhar-park-sunset',
      type: 'visit',
      titleEn: 'Sunset at Al-Azhar Park',
      titleAr: 'غروب في حديقة الأزهر',
      summaryEn: 'The best view in Cairo costs 10 EGP and takes 10 minutes from Khan el-Khalili.',
      summaryAr: 'أجمل منظر في القاهرة يكلّف ١٠ جنيهات ويبعد ١٠ دقائق عن خان الخليلي.',
      contentEn: 'Everyone talks about going to the Citadel for a view of Cairo. Fewer people know that Al-Azhar Park gives you an equally stunning panorama — the Citadel to the south, the minarets of al-Gamaliyya to the west, and on a clear day, the pyramids on the horizon. I went on a Friday afternoon just before maghrib. The call to prayer from a dozen mosques simultaneously was one of the most powerful moments of my time in Egypt.',
      contentAr: null,
      coverImageUrl: null,
      submittedByName: 'Omar Farouk',
      submittedByEmail: 'omar@example.com',
      status: 'pending' as const,
      likeCount: 0,
      viewCount: 0,
      createdAt: now,
      publishedAt: null,
      updatedAt: now,
    },
  ];

  await db.insert(experiences).values(rows).onConflictDoNothing();
  console.log(`Seeded ${rows.length} experiences (4 published, 2 pending).`);
}

seedExperiences()
  .then(() => { console.log('Done.'); process.exit(0); })
  .catch((err) => { console.error(err); process.exit(1); });
